//IBMUSERA JOB ACCT#,                                                   JOB00040
//             IBMUSER,       **JOB STATEMENT GENERATED BY SUBMIT**
//             NOTIFY=&SYSUID,
//             MSGLEVEL=(1,1)
//*
//UCAT    EXEC PGM=IDCAMS
//*            LETS CREATE A USERCAT FOR OUR HLQ :)
//SYSPRINT  DD SYSOUT=*
//SYSIN     DD *
  DEFINE USERCATALOG(NAME(USERCAT.ZDO) -
    ICFCATALOG CYLINDERS(5 5))
/*
