//IBMUSERA JOB ACCT#,                                                   JOB00040
//             IBMUSER,       **JOB STATEMENT GENERATED BY SUBMIT**
//             NOTIFY=&SYSUID,
//* ERBIJ
//             MSGLEVEL=(1,1)
//S1      EXEC PGM=IEFBR14
